export const types = {
  SET_USER_UID: '[auth] SET_LOGIN_UID',
  loadAllComplaints: '[complaints] get all the complainst of all users',
  GET_PLACES: '[places] GET_PLACES',
  loadMyComplaints: '[complaints] get the complaints of my user',
  createComplaint: '[createcomplaints] create new complaint',
  USERNAME_VALIDATION: '[validation] Verify that the username is valid',
  EMAIL_VALIDATION: '[validation] Verify that the email is valid',
  PASSWORD_VALIDATION: '[validation] Verify that the password is valid',
  NUMBER_VALIDATION: '[validation] Verify that the number is valid',
  TEXT_VALIDATION: '[validation] Verify that the text is valid',
  ERROR_VALIDATION: '[validation] Show validation error message',
  IS_VALID: '[validation] Shows if the validation is true or false',
  LIKE: '[complaints] onpres Button Like',
  UNLIKE: '[complaints] onpress buton Unlike',
};
